import esbuild from "esbuild";
import process from "process";

const prod = (process.argv[2] === "production");

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const buildOptions = {
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"electron",
        "electron-serve",
	],
	format: "esm",
	target: "es2018",
	logLevel: "info",
	sourcemap: "inline",
	treeShaking: true,
	outfile: "main.js",
	platform: "node",
}

const context = await esbuild.context({...buildOptions});

await context.rebuild();
process.exit(0);